### ISSUE TITLE
From all possibilities of backbone atoms in res_atoms.dat - need to include logic for simple trims

### ISSUE THREAD

**Issue by natedey** [natedey/RINRUS#22]
RINRUS can't currently handle the situation where the only backbone atoms interacting with seed are the carbon alpha and it's hydrogen. If this is the case, then there are two outcomes:
1) If the sidechain is included in the model, we wouldn't want to add additional backbone, because the C_alpha trimmed to CH3R would be captured in the sidechain fragment
2) If the sidechain isn't included in the model, there needs to be some default trimming behavior based on if neighboring residues are in the model or will eventually be added.

**Comment by dwappett** [comment]
Issue solved now - if only CA or HA selected, both sides of main chain added to anchor it
