### ISSUE TITLE
can't put chain ID into pymol_scripts

### ISSUE THREAD

**Issue by natedey** [natedey/RINRUS#43]
python3 $HOME/git/RINRUS/bin/pymol_scripts.py -ignore_ids "300,301,302" -pdbfilename res_.pdb

What if we have seed res id#s that are duplicated in another chain, which will happen frequently?
I currently have a situation where A:1 and B:145 are defined as the seed, with chain B containing the entire protein. 

python3 $HOME/git/RINRUS/bin/pymol_scripts.py -ignore_ids "1,145" -pdbfilename res_.pdb
will ignore protonation on B:1 which might cause problems

**Comment by dwappett** [comment]
fixed this a little while ago, pymol protonation script now can handle chain:ID specifications
