### ISSUE TITLE
driver is acting funny on bigblue - from pathlib import path in RINRUS_driver.py hanging

### ISSUE THREAD

**Issue by natedey** [natedey/RINRUS#46]
line 5 of RINRUS_driver.py:
from pathlib import Path 
is using python2 code and perhaps not packaged with bigblue python modules
it's hanging when Domi runs it.

I'm seeing problems with shutil not being able to open/read 1.inp in line 394

**Comment by dwappett** [comment]
This has all been fixed when I cleaned up the driver
